#+title: SigmaVimRC

*THIS SOFTWARE IS IN ALPHA, IT MIGHT JUST NOT WORK AS DESCRIBED*
(even though it's also Sigma)

You might have already seen NvChad, but you use Vim or want a simpler config
and be a Chad too? SigmaVimRC was made for you.

............................................................
............................... ... ........................
..................... ......'...,,.... .....................
...................  ..'''''',''';;;;'......................
................... ..',,;:::cclodxxdo;.....................
..................  ...''',,,;:ccllllc;.....................
..................   ...',;::::clllcc:,.....................
................... .... ............','....................
......................      ...      ..',,..................
......................... ...:;.....',,'....................
...................  .......'cl,.'......''..................
...................    ...........'..  .....................
...................             ....   .....................
...................           ...  .    ....................
.....................                 ......................
.....................                .......................
.....................               ...''...................
....................               ....';::,................
................'...              ....'';:clool:,...........
..........',,''.....             ....',;:ccccloodddl;.......
.......,;;;;,''......           ..',;:cloooooodoooodddl;'...
',,,;;:::;;;;,''''....         ...';:clloloooooddoodxxxxdddd
;:::::::::;;;,,,''...............';:cllllcllloooodddddddddoo
;;;;;;;;;;;;;;,,,'''......'''....',;::cccccllllllllllllllllc
,,,,,,,,,;;;;;;;,,,,,,,,,,,,;'...'',;:::ccllllllllccc::;;;;;
....'',,,,,,;;;;;;;;;;;;;;;;;,..',,;;:::cclllccccc::;;,''.''
......'''',,,,,;;;;;;;;;;;;::'..'',;;::::ccccc::::;,,,'.....
. ........'''',,,;;;;;;;;,;;;....'',,,;;;;;;;;;;,,,''....   
   ...........'',,,,,,;;;;;;;.....'''',,,,,,''''........    
    ............''''''''''''.............'............

** Why another Vim distribution

First of all, most of "Vim" distros, are Neovim distros. Sigma is compatible
with Vim and Neovim.

Most of these distributions are pretty complex, and usually require some Lua
knowledge, and happen to be a pain to actually replace some base plugins.

** What is Sigma

Sigma is meant to be simple. It uses vim-plug as plugin manager, which is also
wrapped in sigma#add, sigma#remove and sigma#init functions, which allows full
control what plugins from base set are actually used.

Sigma itself is a plugin.

Sigma comes with sane (or maybe opinionated?) defaults and utilities to make
your vimrc (or init.vim) as small and readable as possible.

Sigma comes with kyotonight.vim theme, which might easily be changed to any
theme of your choice. There is also a plan of adding a possibility to create
your own colorscheme providing just color palette.

Sigma uses fzf which powers all the fuzzy finding in the default config.

Sigma includes a few quality of life plugins, doesn't include a classic file
tree plugin (it uses nnn.vim, which requires nnn file manager). More details
in defualt plugins list.

** Installation

Install vim-plug first:

*** Vim

#+begin_src sh
curl -fLo ~/.vim/autoload/plug.vim --create-dirs \
    https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
#+end_src

*** Neovim

#+begin_src sh
sh -c 'curl -fLo "${XDG_DATA_HOME:-$HOME/.local/share}"/nvim/site/autoload/plug.vim --create-dirs \
       https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'
#+end_src

Install SigmaVimRc:

*** Vim

#+begin_src sh
mkdir ~/.vim/plugged
git clone git@github.com:laniusone/SigmaVimRc.git \
    ~/.vim/plugged/SigmaVimRc
#+end_src

*** Neovim

#+begin_src sh
sh -c 'curl -fLo "${XDG_DATA_HOME:-$HOME/.local/share}"/nvim/site/autoload/sigma.vim --create-dirs \
       https://raw.githubusercontent.com/laniusone/SigmaVimRc/sigma.vim'
#+end_src

** Configuration

To use the default SigmaVimRc just add this line to your .vimrc or init.lua:

*** vimrc

#+begin_src vim
call sigma#init()
#+end_src

*** init.lua

#+begin_src lua
vim.cmd[[call sigma#init()]]
#+end_src

*** Overriding configuration

To override default Sigma configuration... just set your configuration changes
after calling sigma#init function. That includes plugin configurations.

*** Plugins

To remove a plugin:

#+begin_src vim
call sigma#remove('plugin/name')
#+end_src

Add a plugin:

#+begin_src vim
call sigma#add('plugin/name', {'branch': 'master'}) " optional params
#+end_src

These functions need to be called *BEFORE* sigma#init.

*** Extra functions

- sigma#run - opens a split in kitty or tmux, running a supplied command in
current working directory, or no command is supplied it just opens the terminal.

**** Examples

#+begin_src vim
" Run lazygit in current working directory
nnoremap <silent><leader>gg <Cmd>call sigma#run("lazygit -p")<CR>
" Open terminal in current working directory
nnoremap <silent><leader>tt <Cmd>call sigma#run()<CR>
#+end_src

*** LSP

Sigma by default includes coc.nvim for LSP support, but it is not configured
to avoid including large configuration file which you might not need in the
end. So, you will need to add configuration yourself. It's available in
coc.nvim [[https://github.com/neoclide/coc.nvim#example-vim-configuration][README]] file.

You are also free to use whatever you want. Go your way like the lone wolf. 烈
